[automationgateway]
vm1.lab.local

# This section is for your AAP Controller host(s)
# -----------------------------------------------------
[automationcontroller]
vm1.lab.local

# This section is for your AAP Automation Hub host(s)
# -----------------------------------------------------
[automationhub]
vm1.lab.local

# This section is for your AAP EDA Controller host(s)
# -----------------------------------------------------
[automationeda]
vm1.lab.local

# This section is for the AAP database
# -----------------------------------------------------
[database]
vm1.lab.local

[all:vars]
# Ansible
ansible_connection=local
automation_gateway_host="vm1.lab.local"
automation_gateway_url="https://vm1.lab.local"
automation_gateway_proxy_url="https://vm1.lab.local"
client_request_timeout=240
redis_mode=standalone

# Common variables
# https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/containerized_installation/appendix-inventory-files-vars#general-variables
# -----------------------------------------------------
postgresql_admin_username=postgres
postgresql_admin_password=redhat
#gateway_redis_password="redhat"

registry_username="11009103|ddoan"
registry_password="eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiIwZTZkNjdjODc0MmY0YWE2ODcxZTBmMDhiNjczZDExZSJ9.lUbdnL7kZXz7EYOt8ju4TUwrUbRMvnb4b2ZGkP_v1yCGPU2Ce8SV3pVH0zYKoRkCIrWM45Tcag0bP3o08WJsZi4dYPcSKJdLdD5lkyJj4ez6NP-zPfQLAd-I-6r3-Hwy-c58w2Ud4Bhr-NwVExFuDXDFTZPt0JGWWrnp5kZP6sEK8vSckcp4LqiGHODVTjlr9_IkrTpCllBBs0yXLP-xC_7WahQbgg2L_8suGT8sgnZa1keh7eHZSxMaLNZCJ6OFOxwJ9MADlWk8_kD7-KZMAJ50yvdy8t7cyGyIn4lROYuY5FMzufv4H6yJwoZrUOrX6g5ib2IkET-QP708jSz95D7tDRoftdQeFpbMBhIBYZA3e-pG_fXEwNvzBXmeBgSnFaPXI43CgNGlXkcaqwlUje8OQnOc6-ye2gyagwcg57ldHB_ani5Qv66nwWGcE6mku_naMsK8cL0e4Shn-rbsRKyakQLJEOPsh8bSuskNpDYL70_5pdRabk2LYDcOsX9rOPkU6GEaiszhNbhtYVm6JrGk5TR7CeFYf2RcVCJYLgaEz3S8biukED2HFf0EHIPPdr1yc-K1diFQw8yCZBJ24fUAnHpN6446pGvbZviujyibTUN3HKyG2OPxbbGbHI4IIV_1oLS4rQjigrZGOjseBUX47WSoDExmU1Wj4w4o9iI"

#gateway_redis_username="gateway"
#gateway_redis_password="redhat"

# AAP Controller
# https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/containerized_installation/appendix-inventory-files-vars#controller-variables
# -----------------------------------------------------
controller_admin_password=redhat
controller_pg_host=vm1.lab.local
controller_pg_password=redhat
controller_percent_memory_capacity=0.5

# AAP Automation Hub
# https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/containerized_installation/appendix-inventory-files-vars#hub-variables
# -----------------------------------------------------
hub_admin_password=redhat
hub_pg_host=vm1.lab.local
hub_pg_password=redhat
hub_seed_collections=false


# AAP EDA Controller
# https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/containerized_installation/appendix-inventory-files-vars#event-driven-ansible-variables
# -----------------------------------------------------
eda_admin_password=redhat
eda_pg_host=vm1.lab.local
eda_pg_password=redhat


