---
- name: Monitor httpd and trigger Arduino remediation
  hosts: vm1.lab.local
  sources:
    - ansible.eda.url_check:
        urls:
          - https://192.168.122.158
        verify_ssl: false
        delay: 10

  rules:
    # - name: Debug all incoming events
    #   condition: event.url_check is defined
    #   action:
    #     debug:
    #       var: event
        
    - name: If httpd is unreachable, deploy Arduino code
      condition: event.url_check.status == "down"
      action:
        debug:
          var: event
        run_job_template:
          name: "remediate"
          organization: "Default"
