---
- name: Remediation
  hosts: vm2.lab.local
  become: yes
  vars:
    ansible_become_user: shadow
    ansible_become_password: redhat
    
  tasks:
    - name: Ensure httpd service is stopped
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Log the deployment
      ansible.builtin.debug:
        msg: "Arduino remediate.ino deployed successfully! Normal behavior resumed."
      when: upload_result.rc == 0
      
